version: "2"
run:
  concurrency: 2
linters:
  default: none
  enable:
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    govet:
      enable:
        - shadow
  exclusions:

    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Potential HTTP request made with variable url
      - linters:
          - gosec
        text: SQL string concatenation
      - linters:
          - revive
        path: 'util/*'
        text: 'var-naming: avoid meaningless package names'
    paths:
      - vendor
      - docs
      - baseimages
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - docs
      - baseimages
      - third_party$
      - builtin$
      - examples$
