run:
  concurrency: 2
  deadline: 1m
  skip-dirs:
    - vendor
    - docs
    - baseimages
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
issues:
  exclude-rules:
    - text: "Potential HTTP request made with variable url"
      linters:
        - gosec
    - text: "SQL string concatenation"
      linters:
        - gosec