sudo: false

language: go

go:
  - 1.9
  - master

matrix:
  # Allow failures if the code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  
  # Don't block on tip tests. Mark the build as green if tests pass on stable versions.
  fast_finish: true

install:
  - go get github.com/golang/lint/golint
  - mkdir -p $GOPATH/src/golang.org/x && git clone https://github.com/golang/lint.git $GOPATH/src/golang.org/x/lint && go get -u golang.org/x/lint/golint

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - make

notifications:
  email: false