version: "{build}"

clone_folder: c:\gopath\src\github.com\Azure\acr-builder

environment:
  GOPATH: c:\gopath

init:
  - git config --global core.autocrlf true

install:
  - set Path=c:\go\bin;c:\gopath\bin;
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build -o acb.exe .\cmd\acb
  - go test ./...