[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[override]]
  name = "github.com/docker/docker"
  source = "github.com/moby/moby"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true