[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/docker/docker"
  source = "github.com/moby/moby"
  revision = "61138fb5fc0f5fc1799cabfa86d28fb88a0f472c"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.15.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"