[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true