#!/bin/bash

set -e -o pipefail

# binary will be $(go env GOPATH)/bin/golangci-lint
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.50.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
