# Turning dependabot off
# version: 1
# update_configs:
#   - package_manager: "go:modules"
#     directory: "/"
#     update_schedule: "monthly"
#     default_reviewers:
#       - "northtyphoon"
#       - "juliusl"
#     default_labels:
#       - "dependencies"
